import { Injectable } from '@angular/core';
import { NotificationMessage, NotificationTitle } from '../models/notification.model';

@Injectable({ providedIn: 'root' })
export class MediaUploaderService {
  public notificationTitle: NotificationTitle = {
    ChangePassword: "Change Password?",
    ChangeStatus: "Change Status?",
    Close: "Close?",
    Delete: "Delete?",
    Error: "Oh No!",
    Invalid: "Invalid!",
    LoginFailed: "Login Failed!",
    Lock: "Lock?",
    Unauthorized: "Unauthorized!",
    Reset: "Reset?",
    Remove: "Remove?",
    Success: "Well Done!",
    Update: "Update?",
    Warning: "Warning!",
  };
  public notificationMessage: NotificationMessage = {
    Add: "Are you sure you want to add?",
    AddFailed: "Adding failed on save.",
    AddSuccessful: "Successfully added.",
    Close: "Are you sure you want to close?",
    CloseFailed: "Closing failed on save.",
    CloseSuccessful: "Successfully closed.",
    ChangeStatus: "Are you sure you want to change status?",
    ChangeStatusFailed: "Changing status failed on save.",
    ChangeStatusSuccessful: "Status successfully changed.",
    ChangePassword: "Are you sure you want to change password?",
    ChangePasswordFailed: "Changing password failed on save.",
    ChangePasswordSuccessful: "Password successfully changed.",
    ConfirmPassword: "New password and confirm password does not match.",
    Copied: "Copied to clipboard",
    DataNotFound: "Data not found.",
    Delete: 'Are you sure you want to delete?',
    DeleteFailed: "Deleting failed on save.",
    DeleteSuccessful: "Successfully deleted.",
    FileUnselected: "Please select a file.",
    InvalidFileType: "Invalid file type.",
    InvalidFileSize: "Invalid file size.",
    InvalidSearch: "Please complete at least one field.",
    InvalidOTP: "Invalid OTP.",
    LoginSuccessful: "Welcome to the system.",
    LogoutSuccessful: "You have been logged out.",
    LoginFailed: "Your username and/or password do not match.",
    Lock: "Are you sure you want to lock?",
    LockFailed: "Locking failed on save.",
    LockSuccessful: "Successfully locked.",
    NoData: "No data.",
    NoDataSelected: "No data selected.",
    UploadSuccessful: "Successfully uploaded.",
    UploadFailed: "Uploading failed on save.",
    Update: "Are you sure you want to update?",
    UpdateFailed: "Updating Failed On Save.",
    UpdateSuccessful: "Successfully Updated.",
    Remove: "Are you sure you want to remove?",
    RemoveFailed: "Removing failed on save.",
    RemoveSuccessful: "Successfully removed.",
    Reset: "Are you sure you want to reset?",
    ResetFailed: "Reseting failed on save.",
    ResetSuccessful: "Successfully reset.",
    RequiredFields: "Please complete all required fields.",
    SystemError: "An error occurred while connecting to the server.",
    Unauthorized: "You are not authorized to view this page.",
    UnknownError: "An error occurred while processing your request.",
  }
}
